const Map<String, String> appStringsEn = {
  'appName': 'HomeBox',
  'appTagline': 'Organize your entire home',
  'welcomeTitle': 'Welcome to',
  'welcomeSubtitle': 'HomeBox',
  'welcomeDesc': 'Track furniture, appliances, bills, warranties, manuals & repairs — all in one place.',
  'homeSubtitle': 'Manage everything in your home',
  'homeModulesTitle': 'Modules',
  'getStarted': 'Get started',
  'tabHome': 'Home',
  'tabSearch': 'Search',
  'tabStats': 'Stats',
  'tabNotifications': 'Alerts',
  'tabShop': 'Shop',
  'tabProfile': 'Profile',
  'navShop': 'Shop',
  'navSettings': 'Settings',
  'welcomeUser': 'Welcome, {name}!',
  'goodMorning': 'Good Morning',
  'goodAfternoon': 'Good Afternoon',
  'goodEvening': 'Good Evening',
  'roomAll': 'All house',
  'roomLiving': 'Living room',
  'roomBedroom': 'Bed room',
  'roomBathroom': 'Bathroom',
  'roomKitchen': 'Kitchen',
  'changeRoomPhoto': 'Change photo',
  'changeRoomPhotoTitle': 'Photo for {room}',
  'roomPhotoUpdated': '{room} photo updated',
  'resetRoomPhoto': 'Use default photo',
  'roomPhotoReset': 'Default room photo restored',
  'smartDevices': 'Appliances',
  'addNewDevice': 'Add appliance',
  'modStorage': 'Storage',
  'modStorageDesc': 'Track stored items',
  'modFurniture': 'Furniture',
  'modFurnitureDesc': 'Manage home furniture',
  'modElectrical': 'Electrical',
  'modElectricalDesc': 'Track appliances & electronics',
  'modBills': 'Bills',
  'modBillsDesc': 'Track household bills',
  'modWarranty': 'Warranty',
  'modWarrantyDesc': 'Warranty & expiry dates',
  'modPdf': 'PDF Guides',
  'modPdfDesc': 'Manuals & instructions',
  'modRepair': 'Repair Costs',
  'modRepairDesc': 'Track repair expenses',
  'itemsCount': '{count} items',
  'devicesCount': '{count} devices',
  'billsDue': '{count} bills due',
  'warrantyExpiring': '{count} expiring',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'title': 'Title',
  'description': 'Description',
  'location': 'Location',
  'quantity': 'Quantity',
  'amount': 'Amount',
  'date': 'Date',
  'dueDate': 'Due Date',
  'purchaseDate': 'Purchase Date',
  'expiryDate': 'Expiry Date',
  'serialNumber': 'Serial Number',
  'contractor': 'Contractor',
  'repairCost': 'Repair Cost',
  'repairDate': 'Repair Date',
  'isPaid': 'Paid',
  'markPaid': 'Mark as paid',
  'addItem': 'Add item',
  'addBill': 'Add bill',
  'addWarranty': 'Add warranty',
  'addPdf': 'Add PDF guide',
  'addRepair': 'Add repair',
  'addFurniture': 'Add furniture',
  'addStorage': 'Add storage item',
  'addDevice': 'Add device',
  'emptyList': 'No items yet. Tap + to add.',
  'searchHint': 'Search items, bills, devices...',
  'searchEmpty': 'No results found',
  'power': 'Power',
  'on': 'On',
  'off': 'Off',
  'modeAuto': 'Auto',
  'modeCool': 'Cool',
  'modeHeat': 'Heat',
  'modeDry': 'Dry',
  'outsideTemp': 'Outside {temp}°',
  'targetTemperature': 'Target temperature',
  'tempHint': 'Set your preferred temperature (°C). This is saved locally — not connected to real devices.',
  'tempOptionalHint': 'Leave empty for lights, fans, etc.',
  'deleteConfirm': 'Delete "{title}"?',
  'deleteConfirmBody': 'This action cannot be undone.',
  'notifications': 'Notifications',
  'noNotifications': 'No alerts right now',
  'billDueSoon': 'Bill due: {title}',
  'warrantyExpiringSoon': 'Warranty expiring: {title}',
  'statsOverview': 'Home Overview',
  'totalDevices': 'Appliances',
  'activeDevices': 'Total items',
  'totalItemsLabel': 'All items',
  'categoryOverview': 'Items by category',
  'unpaidBills': 'Unpaid Bills',
  'totalRepair': 'Total Repairs',
  'weeklyOverview': 'Weekly Overview',
  'premiumChartsLocked': 'Unlock Premium Stats in Shop',
  'profile': 'Profile',
  'myShop': 'Shop',
  'coins': 'Coins',
  'stars': 'Stars',
  'yourWallet': 'Your Wallet',
  'dailyReward': 'Daily Reward',
  'claim': 'Claim',
  'claimed': 'Claimed',
  'purchaseSuccess': 'Purchase successful!',
  'purchaseFailed': 'Purchase failed',
  'insufficientCoins': 'Not enough coins',
  'alreadyOwned': 'Already owned',
  'coinsAdded': '+{amount} stars added!',
  'removeAdsUnlocked': 'Ads removed!',
  'dailyRewardClaimed': '+{amount} stars — Daily reward!',
  'taskRewardEarned': '+{amount} stars — Task reward!',
  'goalRewardEarned': '+{amount} stars — Milestone reward!',
  'streakRewardEarned': '+{amount} stars — Streak bonus!',
  'coinRewardSub': 'Balance: {balance} stars',
  'shopRemoveAds': 'Remove Ads',
  'shopRemoveAdsDesc': 'Remove all advertisements permanently',
  'shopThemeOcean': 'Ocean Theme',
  'shopThemeOceanDesc': 'Cool blue ocean vibes',
  'shopThemeForest': 'Forest Theme',
  'shopThemeForestDesc': 'Fresh green nature theme',
  'shopThemeSunset': 'Sunset Theme',
  'shopThemeSunsetDesc': 'Warm orange sunset colors',
  'shopThemeLavender': 'Lavender Theme',
  'shopThemeLavenderDesc': 'Soft purple lavender theme',
  'shopBgClouds': 'Cloud Background',
  'shopBgCloudsDesc': 'Soft cloud gradient background',
  'shopBgStars': 'Starry Night',
  'shopBgStarsDesc': 'Deep space star background',
  'shopBgRainbow': 'Rainbow Background',
  'shopBgRainbowDesc': 'Colorful rainbow gradient',
  'shopBgAurora': 'Aurora Background',
  'shopBgAuroraDesc': 'Northern lights aurora effect',
  'shopSkinSoft': 'Soft Cards',
  'shopSkinSoftDesc': 'Extra rounded soft card style',
  'shopSkinGlass': 'Glass Cards',
  'shopSkinGlassDesc': 'Frosted glass card effect',
  'shopSkinBold': 'Bold Cards',
  'shopSkinBoldDesc': 'Strong bordered card style',
  'shopFeatExport': 'Export Data',
  'shopFeatExportDesc': 'Export all your home data as JSON',
  'shopFeatUnlimited': 'Unlimited Items',
  'shopFeatUnlimitedDesc': 'Add up to 200 items per category',
  'shopFeatStats': 'Premium Stats',
  'shopFeatStatsDesc': 'Advanced home analytics charts',
  'shopFeatBillReminder': 'Bill Reminders',
  'shopFeatBillReminderDesc': 'Get notified before bills are due',
  'shopFeatPdfPro': 'PDF Pro',
  'shopFeatPdfProDesc': 'Unlimited PDF guides storage',
  'shopMenuPremium': 'Premium',
  'shopMenuAll': 'All',
  'shopMenuThemes': 'Themes',
  'shopMenuBackgrounds': 'Backgrounds',
  'shopMenuSkins': 'Skins',
  'shopMenuFeatures': 'Features',
  'shopTitle': 'Shop',
  'shopSubtitle': 'Earn stars or buy packs to unlock themes & features',
  'shopBrowse': 'Browse',
  'shopEmptyCategory': 'No items in this category',
  'buyWithCoins': 'Buy with Stars',
  'buyWithMoney': 'Buy with Google Play',
  'buyWithGooglePlay': 'Buy with Google Play',
  'buyCoinsDesc': 'Choose a star pack to purchase',
  'dailyRewardDone': 'Daily reward already claimed',
  'claimDailyButton': 'Claim +10',
  'earnStepDaily': 'Log in daily for free stars',
  'earnStepLogActivity': 'Add home items',
  'earnStepLogActivityDesc': '+5 stars per item (max 20/day)',
  'earnStepMilestone': 'Complete milestones',
  'earnStepMilestoneDesc': '+8 stars per milestone (max 5/day)',
  'earnStepStreak': 'Keep your streak',
  'earnStepStreakDesc': '+15 stars for daily streak',
  'earnStepBuy': 'Purchase star packs via Google Play',
  'applied': 'Applied!',
  'apply': 'Apply',
  'resetToDefault': 'Reset to default',
  'openingBilling': 'Opening Google Play...',
  'removeAdsIap': 'Remove ads via Google Play',
  'configTimeout': 'Config timeout — using cached settings',
  'configNetworkError': 'Network error — using cached settings',
  'owned': 'Owned',
  'equipped': 'Equipped',
  'equip': 'Equip',
  'resetDefault': 'Reset to Default',
  'settings': 'Settings',
  'darkMode': 'Dark Mode',
  'language': 'Language',
  'userName': 'Your Name',
  'privacyPolicy': 'Privacy Policy',
  'about': 'About',
  'version': 'Version',
  'limitReached': 'Limit reached. Visit Shop to unlock more.',
  'buyCoins': 'Buy Stars',
  'restorePurchases': 'Restore Purchases',
  'billingDisabled': 'Google Play purchases temporarily unavailable',
  'networkError': 'Network error. Using cached settings.',
  'all': 'All',
  'premium': 'Premium',
  'themes': 'Themes',
  'backgrounds': 'Backgrounds',
  'skins': 'Skins',
  'features': 'Features',
  'earnCoins': 'Earn Stars',
  'earnCoinsDesc': 'Add items daily or buy star packs',
  'privacyPolicyTitle': 'Privacy Policy',
  'privacyPolicyBody': 'HomeBox stores all your home management data locally on your device. We do not collect, transmit, or share your personal information with third parties. Furniture, bills, warranties, and device data remain on your device. In-app purchases are processed securely through Google Play Billing. You can export your data at any time from Settings.',
  'yourCoins': '{count} stars',
  'coinPack': 'Pack {num}',
  'coinAmount': '{count} stars',
  'coinAmountTotal': '{count} stars total',
  'coinBonusExtra': '{base} + {bonus} bonus!',
  'processingPurchase': 'Processing purchase...',
  'billingUnavailable': 'Google Play Billing unavailable',
  'productsNotFound': 'Products not configured yet',
  'earnCoinsHint': 'Earn free stars daily or buy packs for instant unlock',
  'firstPurchaseTitle': 'First Purchase Bonus!',
  'firstPurchaseDesc': '+{percent}% extra stars on your first buy',
  'firstPurchaseBadge': '+50% FIRST',
  'hotDealTitle': 'Weekly Hot Deal',
  'hotDealDesc': 'Pack {pack}: +{percent}% bonus (+{bonus} stars)',
  'hotDealBadge': 'HOT',
  'bestValueBadge': 'BEST VALUE',
  'dailySpinTitle': 'Lucky Spin',
  'dailySpinDesc': 'Free spin every day — win up to 100 stars!',
  'spinNow': 'Spin Now!',
  'spinning': 'Spinning...',
  'spinComeBack': 'Come back tomorrow',
  'spinAlreadyDone': 'Already spun today — come back tomorrow!',
  'spinWinTitle': 'You won {coins} stars!',
  'spinRewardEarned': '+{amount} stars — Lucky spin!',
  'wantMoreCoins': 'Want more stars? Buy a pack →',
  'loginStreak': '{days}-day login streak 🔥',
  'unlockProgressTitle': 'Unlock {item}',
  'unlockReadyTitle': 'Ready to unlock {item}!',
  'coinsNeeded': '{count} more',
  'coinsAddedWithBonus': '+{amount} stars (+ bonus)!',
  'homeUnlockTeaser': '{coins} more stars to unlock {item}',
  'selectPdf': 'Select PDF file',
  'openPdf': 'Open PDF',
  'noPdfFile': 'No PDF attached',
  'room': 'Room',
  'paid': 'Paid',
  'unpaid': 'Unpaid',
  'expired': 'Expired',
  'active': 'Active',
  'today': 'Today',
  'noData': 'No data yet',
  'photos': 'Photos',
  'photoCount': '{current}/{max} photos',
  'photoQuotaTotal': '{used}/{max} photos used in app',
  'pickGallery': 'Gallery',
  'takePhoto': 'Take photo',
  'pickMultiple': 'Select multiple',
  'removePhoto': 'Remove photo',
  'photoPickFailed': 'Could not load photo',
  'photoLimitReached': 'Photo limit reached',
  'photoSoftUpgradeHint': 'Running low on photo space. Album Pro adds more room.',
  'photoLimitTitle': 'Photo space full',
  'photoLimitBody': 'You have used {used}/{max} free photos. Upgrade for 10 photos per item and 500 total.',
  'learnMore': 'Learn more',
  'unlockForStars': 'Unlock for {price} stars',
  'maybeLater': 'Maybe later',
  'ok': 'OK',
  'shopFeatPhotoAlbum': 'Album Pro',
  'shopFeatPhotoAlbumDesc': '10 photos per item · 500 total · batch upload',
};
