const Map<String, String> appStringsVi = {
  'appName': 'HomeBox',
  'appTagline': 'Quản lý toàn bộ ngôi nhà',
  'welcomeTitle': 'Chào mừng đến',
  'welcomeSubtitle': 'HomeBox',
  'welcomeDesc': 'Theo dõi nội thất, thiết bị, hóa đơn, bảo hành, tài liệu & sửa chữa — tất cả trong một app.',
  'homeSubtitle': 'Quản lý mọi thứ trong nhà',
  'homeModulesTitle': 'Danh mục',
  'getStarted': 'Bắt đầu',
  'tabHome': 'Trang chủ',
  'tabSearch': 'Tìm kiếm',
  'tabStats': 'Thống kê',
  'tabNotifications': 'Thông báo',
  'tabShop': 'Cửa hàng',
  'tabProfile': 'Cá nhân',
  'navShop': 'Cửa hàng',
  'navSettings': 'Cài đặt',
  'welcomeUser': 'Chào, {name}!',
  'goodMorning': 'Chào buổi sáng',
  'goodAfternoon': 'Chào buổi chiều',
  'goodEvening': 'Chào buổi tối',
  'roomAll': 'Toàn nhà',
  'roomLiving': 'Phòng khách',
  'roomBedroom': 'Phòng ngủ',
  'roomBathroom': 'Phòng tắm',
  'roomKitchen': 'Nhà bếp',
  'changeRoomPhoto': 'Đổi ảnh',
  'changeRoomPhotoTitle': 'Ảnh {room}',
  'roomPhotoUpdated': 'Đã cập nhật ảnh {room}',
  'resetRoomPhoto': 'Dùng ảnh mặc định',
  'roomPhotoReset': 'Đã khôi phục ảnh mặc định',
  'smartDevices': 'Thiết bị điện',
  'addNewDevice': 'Thêm thiết bị',
  'modStorage': 'Lưu',
  'modStorageDesc': 'Quản lý đồ lưu trữ',
  'modFurniture': 'Nội thất',
  'modFurnitureDesc': 'Quản lý nội thất',
  'modElectrical': 'Thiết bị điện',
  'modElectricalDesc': 'Theo dõi thiết bị & đồ điện',
  'modBills': 'Hóa đơn',
  'modBillsDesc': 'Theo dõi hóa đơn',
  'modWarranty': 'Bảo hành',
  'modWarrantyDesc': 'Theo dõi bảo hành',
  'modPdf': 'Hướng dẫn PDF',
  'modPdfDesc': 'Sách hướng dẫn & tài liệu',
  'modRepair': 'Chi phí sửa chữa',
  'modRepairDesc': 'Theo dõi chi phí sửa chữa',
  'itemsCount': '{count} mục',
  'devicesCount': '{count} thiết bị',
  'billsDue': '{count} hóa đơn sắp đến hạn',
  'warrantyExpiring': '{count} bảo hành sắp hết',
  'save': 'Lưu',
  'cancel': 'Hủy',
  'delete': 'Xóa',
  'edit': 'Sửa',
  'title': 'Tiêu đề',
  'description': 'Mô tả',
  'location': 'Vị trí',
  'quantity': 'Số lượng',
  'amount': 'Số tiền',
  'date': 'Ngày',
  'dueDate': 'Hạn thanh toán',
  'purchaseDate': 'Ngày mua',
  'expiryDate': 'Ngày hết hạn',
  'serialNumber': 'Số serial',
  'contractor': 'Nhà thầu',
  'repairCost': 'Chi phí sửa chữa',
  'repairDate': 'Ngày sửa chữa',
  'isPaid': 'Đã thanh toán',
  'markPaid': 'Đánh dấu đã trả',
  'addItem': 'Thêm mục',
  'addBill': 'Thêm hóa đơn',
  'addWarranty': 'Thêm bảo hành',
  'addPdf': 'Thêm PDF',
  'addRepair': 'Thêm sửa chữa',
  'addFurniture': 'Thêm nội thất',
  'addStorage': 'Thêm đồ lưu',
  'addDevice': 'Thêm thiết bị',
  'emptyList': 'Chưa có dữ liệu. Nhấn + để thêm.',
  'searchHint': 'Tìm đồ, hóa đơn, thiết bị...',
  'searchEmpty': 'Không tìm thấy kết quả',
  'power': 'Nguồn',
  'on': 'Bật',
  'off': 'Tắt',
  'modeAuto': 'Tự động',
  'modeCool': 'Lạnh',
  'modeHeat': 'Nóng',
  'modeDry': 'Khô',
  'outsideTemp': 'Ngoài trời {temp}°',
  'targetTemperature': 'Nhiệt độ mục tiêu',
  'tempHint': 'Đặt nhiệt độ mong muốn (°C). Chỉ lưu trên app — chưa kết nối thiết bị thật.',
  'tempOptionalHint': 'Để trống nếu là đèn, quạt, v.v.',
  'deleteConfirm': 'Xóa "{title}"?',
  'deleteConfirmBody': 'Thao tác này không thể hoàn tác.',
  'notifications': 'Thông báo',
  'noNotifications': 'Không có thông báo',
  'billDueSoon': 'Hóa đơn sắp đến hạn: {title}',
  'warrantyExpiringSoon': 'Bảo hành sắp hết: {title}',
  'statsOverview': 'Tổng quan nhà',
  'totalDevices': 'Thiết bị điện',
  'activeDevices': 'Tổng mục',
  'totalItemsLabel': 'Tất cả mục',
  'categoryOverview': 'Theo danh mục',
  'unpaidBills': 'Hóa đơn chưa trả',
  'totalRepair': 'Tổng sửa chữa',
  'weeklyOverview': 'Tổng quan tuần',
  'premiumChartsLocked': 'Mở khóa Thống kê Premium tại Cửa hàng',
  'profile': 'Cá nhân',
  'myShop': 'Cửa hàng',
  'coins': 'Sao',
  'stars': 'Sao',
  'yourWallet': 'Ví của bạn',
  'dailyReward': 'Phần thưởng hàng ngày',
  'claim': 'Nhận',
  'claimed': 'Đã nhận',
  'purchaseSuccess': 'Mua thành công!',
  'purchaseFailed': 'Mua thất bại',
  'insufficientCoins': 'Không đủ sao',
  'alreadyOwned': 'Đã sở hữu',
  'coinsAdded': '+{amount} sao đã thêm!',
  'removeAdsUnlocked': 'Đã gỡ quảng cáo!',
  'dailyRewardClaimed': '+{amount} sao — Phần thưởng hàng ngày!',
  'taskRewardEarned': '+{amount} sao — Phần thưởng hoàn thành!',
  'goalRewardEarned': '+{amount} sao — Phần thưởng cột mốc!',
  'streakRewardEarned': '+{amount} sao — Phần thưởng chuỗi ngày!',
  'coinRewardSub': 'Số dư: {balance} sao',
  'shopRemoveAds': 'Gỡ quảng cáo',
  'shopRemoveAdsDesc': 'Gỡ quảng cáo vĩnh viễn',
  'shopThemeOcean': 'Theme Đại dương',
  'shopThemeOceanDesc': 'Tông xanh biển mát mẻ',
  'shopThemeForest': 'Theme Rừng',
  'shopThemeForestDesc': 'Tông xanh thiên nhiên',
  'shopThemeSunset': 'Theme Hoàng hôn',
  'shopThemeSunsetDesc': 'Tông cam ấm áp',
  'shopThemeLavender': 'Theme Lavender',
  'shopThemeLavenderDesc': 'Tông tím nhẹ nhàng',
  'shopBgClouds': 'Nền Mây',
  'shopBgCloudsDesc': 'Gradient mây mềm mại',
  'shopBgStars': 'Đêm sao',
  'shopBgStarsDesc': 'Nền không gian đầy sao',
  'shopBgRainbow': 'Nền Cầu vồng',
  'shopBgRainbowDesc': 'Gradient cầu vồng',
  'shopBgAurora': 'Nền Cực quang',
  'shopBgAuroraDesc': 'Hiệu ứng cực quang',
  'shopSkinSoft': 'Thẻ mềm',
  'shopSkinSoftDesc': 'Bo góc mềm mại',
  'shopSkinGlass': 'Thẻ kính',
  'shopSkinGlassDesc': 'Hiệu ứng kính mờ',
  'shopSkinBold': 'Thẻ đậm',
  'shopSkinBoldDesc': 'Viền đậm nổi bật',
  'shopFeatExport': 'Xuất dữ liệu',
  'shopFeatExportDesc': 'Xuất toàn bộ dữ liệu nhà dạng JSON',
  'shopFeatUnlimited': 'Không giới hạn',
  'shopFeatUnlimitedDesc': 'Thêm tối đa 200 mục mỗi loại',
  'shopFeatStats': 'Thống kê Premium',
  'shopFeatStatsDesc': 'Biểu đồ phân tích nâng cao',
  'shopFeatBillReminder': 'Nhắc hóa đơn',
  'shopFeatBillReminderDesc': 'Thông báo trước hạn thanh toán',
  'shopFeatPdfPro': 'PDF Pro',
  'shopFeatPdfProDesc': 'Lưu trữ PDF không giới hạn',
  'shopMenuPremium': 'Premium',
  'shopMenuAll': 'Tất cả',
  'shopMenuThemes': 'Theme',
  'shopMenuBackgrounds': 'Hình nền',
  'shopMenuSkins': 'Skin',
  'shopMenuFeatures': 'Chức năng',
  'shopTitle': 'Cửa hàng',
  'shopSubtitle': 'Cày sao hoặc mua gói để mở khóa theme & chức năng',
  'shopBrowse': 'Khám phá',
  'shopEmptyCategory': 'Không có sản phẩm trong danh mục',
  'buyWithCoins': 'Mua bằng Sao',
  'buyWithMoney': 'Mua qua Google Play',
  'buyWithGooglePlay': 'Mua qua Google Play',
  'buyCoinsDesc': 'Chọn gói sao để mua',
  'dailyRewardDone': 'Đã nhận phần thưởng hôm nay',
  'claimDailyButton': 'Nhận +10',
  'earnStepDaily': 'Đăng nhập hàng ngày nhận sao miễn phí',
  'earnStepLogActivity': 'Thêm mục nhà',
  'earnStepLogActivityDesc': '+5 sao mỗi mục (tối đa 20/ngày)',
  'earnStepMilestone': 'Hoàn thành cột mốc',
  'earnStepMilestoneDesc': '+8 sao mỗi cột mốc (tối đa 5/ngày)',
  'earnStepStreak': 'Duy trì chuỗi ngày',
  'earnStepStreakDesc': '+15 sao cho chuỗi ngày',
  'earnStepBuy': 'Mua gói sao qua Google Play',
  'applied': 'Đã áp dụng!',
  'apply': 'Áp dụng',
  'resetToDefault': 'Đặt lại mặc định',
  'openingBilling': 'Đang mở Google Play...',
  'removeAdsIap': 'Gỡ quảng cáo qua Google Play',
  'configTimeout': 'Hết thời gian — dùng cài đặt đã lưu',
  'configNetworkError': 'Lỗi mạng — dùng cài đặt đã lưu',
  'owned': 'Đã sở hữu',
  'equipped': 'Đang dùng',
  'equip': 'Áp dụng',
  'resetDefault': 'Đặt lại mặc định',
  'settings': 'Cài đặt',
  'darkMode': 'Chế độ tối',
  'language': 'Ngôn ngữ',
  'userName': 'Tên của bạn',
  'privacyPolicy': 'Chính sách bảo mật',
  'about': 'Giới thiệu',
  'version': 'Phiên bản',
  'limitReached': 'Đã đạt giới hạn. Vào Cửa hàng để mở thêm.',
  'buyCoins': 'Mua Sao',
  'restorePurchases': 'Khôi phục mua hàng',
  'billingDisabled': 'Mua hàng Google Play tạm không khả dụng',
  'networkError': 'Lỗi mạng. Dùng cài đặt đã lưu.',
  'all': 'Tất cả',
  'premium': 'Premium',
  'themes': 'Theme',
  'backgrounds': 'Hình nền',
  'skins': 'Skin',
  'features': 'Chức năng',
  'earnCoins': 'Kiếm Sao',
  'earnCoinsDesc': 'Thêm mục hàng ngày hoặc mua gói sao',
  'privacyPolicyTitle': 'Chính sách bảo mật',
  'privacyPolicyBody': 'HomeBox lưu trữ toàn bộ dữ liệu quản lý nhà cục bộ trên thiết bị của bạn. Chúng tôi không thu thập, truyền tải hay chia sẻ thông tin cá nhân với bên thứ ba. Dữ liệu nội thất, hóa đơn, bảo hành và thiết bị đều nằm trên thiết bị. Mua trong app được xử lý an toàn qua Google Play Billing. Bạn có thể xuất dữ liệu bất cứ lúc nào từ Cài đặt.',
  'yourCoins': '{count} sao',
  'coinPack': 'Gói {num}',
  'coinAmount': '{count} sao',
  'coinAmountTotal': 'Tổng {count} sao',
  'coinBonusExtra': '{base} + {bonus} thưởng!',
  'processingPurchase': 'Đang xử lý mua hàng...',
  'billingUnavailable': 'Google Play Billing không khả dụng',
  'productsNotFound': 'Sản phẩm chưa được cấu hình',
  'earnCoinsHint': 'Kiếm sao miễn phí hàng ngày hoặc mua gói để mở khóa ngay',
  'firstPurchaseTitle': 'Thưởng mua lần đầu!',
  'firstPurchaseDesc': '+{percent}% sao thêm cho lần mua đầu',
  'firstPurchaseBadge': '+50% ĐẦU TIÊN',
  'hotDealTitle': 'Deal tuần này',
  'hotDealDesc': 'Gói {pack}: +{percent}% thưởng (+{bonus} sao)',
  'hotDealBadge': 'HOT',
  'bestValueBadge': 'GIÁ TỐT',
  'dailySpinTitle': 'Vòng quay may mắn',
  'dailySpinDesc': 'Quay miễn phí mỗi ngày — thắng tới 100 sao!',
  'spinNow': 'Quay ngay!',
  'spinning': 'Đang quay...',
  'spinComeBack': 'Quay lại vào ngày mai',
  'spinAlreadyDone': 'Đã quay hôm nay — quay lại ngày mai!',
  'spinWinTitle': 'Bạn thắng {coins} sao!',
  'spinRewardEarned': '+{amount} sao — Vòng quay may mắn!',
  'wantMoreCoins': 'Muốn thêm sao? Mua gói →',
  'loginStreak': 'Chuỗi {days} ngày 🔥',
  'unlockProgressTitle': 'Mở khóa {item}',
  'unlockReadyTitle': 'Sẵn sàng mở {item}!',
  'coinsNeeded': 'Còn {count}',
  'coinsAddedWithBonus': '+{amount} sao (+ thưởng)!',
  'homeUnlockTeaser': 'Còn {coins} sao để mở {item}',
  'selectPdf': 'Chọn file PDF',
  'openPdf': 'Mở PDF',
  'noPdfFile': 'Chưa có file PDF',
  'room': 'Phòng',
  'paid': 'Đã trả',
  'unpaid': 'Chưa trả',
  'expired': 'Hết hạn',
  'active': 'Đang hoạt động',
  'today': 'Hôm nay',
  'noData': 'Chưa có dữ liệu',
  'photos': 'Hình ảnh',
  'photoCount': '{current}/{max} ảnh',
  'pickGallery': 'Thư viện',
  'takePhoto': 'Chụp ảnh',
  'pickMultiple': 'Chọn nhiều ảnh',
  'removePhoto': 'Xóa ảnh',
  'photoPickFailed': 'Không thể tải ảnh',
  'photoLimitReached': 'Đã đạt giới hạn ảnh',
  'photoSoftUpgradeHint': 'Sắp hết dung lượng ảnh. Album Pro mở thêm chỗ lưu.',
  'photoLimitTitle': 'Đã hết dung lượng ảnh',
  'photoLimitBody': 'Bạn đã dùng {used}/{max} ảnh miễn phí. Nâng cấp để có 10 ảnh/mục và 500 ảnh tổng.',
  'photoQuotaTotal': 'Đã dùng {used}/{max} ảnh trong app',
  'learnMore': 'Tìm hiểu',
  'unlockForStars': 'Mở khóa {price} sao',
  'maybeLater': 'Để sau',
  'ok': 'OK',
  'shopFeatPhotoAlbum': 'Album Pro',
  'shopFeatPhotoAlbumDesc': '10 ảnh/mục · 500 ảnh tổng · chọn nhiều ảnh',
};
